### ISSUE TITLE
[suggestion] use git sub modules

### ISSUE THREAD

**Issue by breningham** [SIMPATICOProject/simpatico-platform#1]
In your readme file you say that we need to manually clone extra git repositorys

I suggest that you add these external repositories as git submodules. 

Read about it here: https://git-scm.com/book/en/v2/Git-Tools-Submodules

This way we can use one command from git to clone everything while keeping the individual repositories separate.

**Comment by mirkoperillo** [comment]
Thank you for the suggestion.

The final idea is to have all components as tagged images in docker hub repository, but this could be a good temporaneous solution.

I'll investigate about that.
